//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsBrowser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBrowser defaultInstance = ((SettingsBrowser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBrowser())));
        
        public static SettingsBrowser Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string Chrome {
            get {
                return ((string)(this["Chrome"]));
            }
            set {
                this["Chrome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("firefox")]
        public string FireFox {
            get {
                return ((string)(this["FireFox"]));
            }
            set {
                this["FireFox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edge")]
        public string Edge {
            get {
                return ((string)(this["Edge"]));
            }
            set {
                this["Edge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IE")]
        public string IE {
            get {
                return ((string)(this["IE"]));
            }
            set {
                this["IE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Valiantsin_Lopan\\Documents\\Visual Studio 2015\\Projects\\TestFramework\\pac" +
            "kages\\Selenium.WebDriver.ChromeDriver.2.27.0\\driver")]
        public string ChromePath {
            get {
                return ((string)(this["ChromePath"]));
            }
            set {
                this["ChromePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Valiantsin_Lopan\\Documents\\Visual Studio 2015\\Projects\\TestFramework\\pac" +
            "kages\\Selenium.Firefox.WebDriver.0.13.0\\driver")]
        public string FireFoxPath {
            get {
                return ((string)(this["FireFoxPath"]));
            }
            set {
                this["FireFoxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://journals.lww.com/")]
        public string URl {
            get {
                return ((string)(this["URl"]));
            }
            set {
                this["URl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\VALIANTSIN\\TAT LAB\\TestFramework\\packages\\Selenium.WebDriver.ChromeDriver.2.27" +
            ".0\\driver")]
        public string ChromePathSony {
            get {
                return ((string)(this["ChromePathSony"]));
            }
            set {
                this["ChromePathSony"] = value;
            }
        }
    }
}
