//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsPaths : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPaths defaultInstance = ((SettingsPaths)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPaths())));
        
        public static SettingsPaths Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\VALIANTSIN\\TAT LAB\\TestFramework task\\Styling\\Responsive-Batch-6.xlsx")]
        public string BatchPath {
            get {
                return ((string)(this["BatchPath"]));
            }
            set {
                this["BatchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bfb {
            get {
                return ((string)(this["bfb"]));
            }
            set {
                this["bfb"] = value;
            }
        }
    }
}
