//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsPaths : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPaths defaultInstance = ((SettingsPaths)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPaths())));
        
        public static SettingsPaths Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Data for training\\Styling\\Responsive-Batch-6.xlsx")]
        public string BatchPath {
            get {
                return ((string)(this["BatchPath"]));
            }
            set {
                this["BatchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dfdfdf {
            get {
                return ((string)(this["dfdfdf"]));
            }
            set {
                this["dfdfdf"] = value;
            }
        }
    }
}
