//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsBrowser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBrowser defaultInstance = ((SettingsBrowser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBrowser())));
        
        public static SettingsBrowser Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string Chrome {
            get {
                return ((string)(this["Chrome"]));
            }
            set {
                this["Chrome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("firefox")]
        public string FireFox {
            get {
                return ((string)(this["FireFox"]));
            }
            set {
                this["FireFox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edge")]
        public string Edge {
            get {
                return ((string)(this["Edge"]));
            }
            set {
                this["Edge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IE")]
        public string IE {
            get {
                return ((string)(this["IE"]));
            }
            set {
                this["IE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Valiantsin_Lopan\\Documents\\Visual Studio 2015\\Projects\\TestFramework\\pac" +
            "kages\\Selenium.WebDriver.ChromeDriver.2.27.0\\driver")]
        public string ChromePath {
            get {
                return ((string)(this["ChromePath"]));
            }
            set {
                this["ChromePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Valiantsin_Lopan\\Documents\\Visual Studio 2015\\Projects\\TestFramework\\pac" +
            "kages\\Selenium.Firefox.WebDriver.0.13.0\\driver")]
        public string FireFoxPath {
            get {
                return ((string)(this["FireFoxPath"]));
            }
            set {
                this["FireFoxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://journals.lww.com/")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
    }
}
